# Form implementation generated from reading ui file 'ui\don_hang_form.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DonHangDialog(object):
    def setupUi(self, DonHangDialog):
        DonHangDialog.setObjectName("DonHangDialog")
        DonHangDialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(DonHangDialog)
        self.verticalLayout.setContentsMargins(QtCore.QRect(24, 20, 24, 20))
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(parent=DonHangDialog)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.formLayout.setHorizontalSpacing(14)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=DonHangDialog)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.txt_ma_don = QtWidgets.QLineEdit(parent=DonHangDialog)
        self.txt_ma_don.setObjectName("txt_ma_don")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txt_ma_don)
        self.label1 = QtWidgets.QLabel(parent=DonHangDialog)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label1)
        self.cbo_xe = QtWidgets.QComboBox(parent=DonHangDialog)
        self.cbo_xe.setObjectName("cbo_xe")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbo_xe)
        self.label2 = QtWidgets.QLabel(parent=DonHangDialog)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label2)
        self.cbo_kh = QtWidgets.QComboBox(parent=DonHangDialog)
        self.cbo_kh.setObjectName("cbo_kh")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbo_kh)
        self.label3 = QtWidgets.QLabel(parent=DonHangDialog)
        self.label3.setObjectName("label3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label3)
        self.cbo_nv = QtWidgets.QComboBox(parent=DonHangDialog)
        self.cbo_nv.setObjectName("cbo_nv")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.cbo_nv)
        self.label4 = QtWidgets.QLabel(parent=DonHangDialog)
        self.label4.setObjectName("label4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label4)
        self.spin_gia_ban = QtWidgets.QDoubleSpinBox(parent=DonHangDialog)
